version: '3'
services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./docker/prometheus/:/etc/prometheus/
    ports:
      - "9090:9090"
    depends_on:
      - test
  grafana:
    image: grafana/grafana
    container_name: grafana
    env_file:
      - ./docker/grafana/grafana.env
    ports:
      - "3000:3000"
  test:
    image: test:0.0.1-SNAPSHOT
    ports:
      - "8080:8080"